//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agente
    {
        public Agente()
        {
            this.GestionFalabella = new HashSet<GestionFalabella>();
        }
    
        public int IdAgente { get; set; }
        public int IdAseguradora { get; set; }
        public string NombreAgente { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Aseguradora Aseguradora { get; set; }
        public virtual ICollection<GestionFalabella> GestionFalabella { get; set; }
    }
}
