//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aseguradora
    {
        public Aseguradora()
        {
            this.Agente = new HashSet<Agente>();
            this.GestionFalabella = new HashSet<GestionFalabella>();
            this.Productos = new HashSet<Productos>();
        }
    
        public int IdAseguradora { get; set; }
        public string NombreAseguradora { get; set; }
        public int Nit { get; set; }
        public int Telefono { get; set; }
        public string Contacto { get; set; }
        public string Direccion { get; set; }
    
        public virtual ICollection<Agente> Agente { get; set; }
        public virtual ICollection<GestionFalabella> GestionFalabella { get; set; }
        public virtual ICollection<Productos> Productos { get; set; }
    }
}
