//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GestionFalabella
    {
        public GestionFalabella()
        {
            this.Productos = new HashSet<Productos>();
        }
    
        public int IdGestion { get; set; }
        public int IdAseguradora { get; set; }
        public int IdAgente { get; set; }
        public string NombreCliente { get; set; }
        public int Cedula { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Direccion { get; set; }
    
        public virtual Agente Agente { get; set; }
        public virtual Aseguradora Aseguradora { get; set; }
        public virtual ICollection<Productos> Productos { get; set; }
    }
}
