//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public Productos()
        {
            this.GestionFalabella = new HashSet<GestionFalabella>();
        }
    
        public int IdProducto { get; set; }
        public int IdAseguradora { get; set; }
        public string NombreProducto { get; set; }
        public int CodigoProducto { get; set; }
    
        public virtual Aseguradora Aseguradora { get; set; }
        public virtual ICollection<GestionFalabella> GestionFalabella { get; set; }
    }
}
